project:
  type: book

book:
  title: "intro-statistics"
  author: "Calvin Williamson"
  date: "7/16/2023"
  chapters:
    - index.Rmd
    - what-is-statistics.Rmd
    - descriptive-and-inferential.Rmd
    - zvalues.Rmd
    - standard-normal-curve.Rmd
    - standard-normal-table.Rmd
    - latex.Rmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: journal
    html-math-method: mathjax
    include-in-header:
      - text: |
          <script>
          window.MathJax = {
            tex: {
              tags: 'ams'
            }
          };
          </script>
  pdf:
    documentclass: scrreprt
