<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>20&nbsp; Confidence Intervals For Proportions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./hypothesis-testing-proportions.html" rel="next">
<link href="./sample-proportions-distribution.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./confidence-intervals-prop.html"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Confidence Intervals For Proportions</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Intro Statistics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Foreward</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./what-is-statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">What is Statistics?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./descriptive-and-inferential.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Descriptive and Inferential Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./population-and-sample.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Population and Sample</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./parameter-and-statistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Parameter and Statistic</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./types-of-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Types of Variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./validity-and-reliability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Validity and Reliability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dotplots-and-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Dotplots and Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./barplots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Barplots</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./central-tendencies.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Central Tendencies</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./measures-of-spread.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Measures of Spread</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./zvalues.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Z-Values</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./standard-normal-curve.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Standard Normal Curve</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./standard-normal-table.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Standard Normal Table</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./standard-normal-areas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Standard Normal Areas</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./standard-normal-spreadsheet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Standard Normal Areas And Spreadsheets</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./backwards-problems.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Backwards Problems</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sample-proportions-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Sampling Distribution of Sample Proportions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./confidence-intervals-prop.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Confidence Intervals For Proportions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hypothesis-testing-proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Hypothesis Testing - Proportions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sample-means-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Sampling Distribution of Sample Means</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./confidence-intervals-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Confidence Intervals For Means</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hypothesis-testing-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Hypothesis Testing - Means</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./simple-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Simple Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression-slope-intercept.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Regression SLOPE and INTERCEPT</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./simple-regression-significance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Is This a Significant Linear Relationship?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression-toolpak.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Using the ToolPak for Regression Modeling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rsquared.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">R-Squared (<span class="math inline">\(r^2\)</span>)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./z-table.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Z Table For Standard Normal Distribution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lines.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Straight Line Review</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#steps-for-finding-confidence-intervals---proportions" id="toc-steps-for-finding-confidence-intervals---proportions" class="nav-link active" data-scroll-target="#steps-for-finding-confidence-intervals---proportions"><span class="header-section-number">20.1</span> Steps for Finding Confidence Intervals - Proportions</a></li>
  <li><a href="#margin-of-error-e-for-confidence-intervals---proportions" id="toc-margin-of-error-e-for-confidence-intervals---proportions" class="nav-link" data-scroll-target="#margin-of-error-e-for-confidence-intervals---proportions"><span class="header-section-number">20.2</span> Margin of Error E for Confidence Intervals - Proportions</a></li>
  <li><a href="#critical-value-zstar" id="toc-critical-value-zstar" class="nav-link" data-scroll-target="#critical-value-zstar"><span class="header-section-number">20.3</span> Critical Value <span class="math inline">\(z^\star\)</span></a></li>
  <li><a href="#confidence-interval-calculations---proportions" id="toc-confidence-interval-calculations---proportions" class="nav-link" data-scroll-target="#confidence-interval-calculations---proportions"><span class="header-section-number">20.4</span> Confidence Interval Calculations - Proportions</a></li>
  <li><a href="#effect-of-changing-confidence-level" id="toc-effect-of-changing-confidence-level" class="nav-link" data-scroll-target="#effect-of-changing-confidence-level"><span class="header-section-number">20.5</span> Effect of Changing Confidence Level</a></li>
  <li><a href="#applications-of-confidence-intervals" id="toc-applications-of-confidence-intervals" class="nav-link" data-scroll-target="#applications-of-confidence-intervals"><span class="header-section-number">20.6</span> Applications of Confidence Intervals</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="confidence-intervals-prop" class="quarto-section-identifier"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Confidence Intervals For Proportions</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>In this section we look at a technique for estimating a population proportion <span class="math inline">\(p\)</span> when we do not know it.</p>
<p>The technique is called <strong>calculating a confidence interval</strong>.</p>
<p>We start by taking a sample and finding a sample proportion <span class="math inline">\(\hat p\)</span>. Then we add and subtract a margin of error <span class="math inline">\(E\)</span> to the sample proportion to make an interval where we hope to find the population proportion. We will show how to calculate the margin of error <span class="math inline">\(E\)</span> below.</p>
<p>We can say using something called the <strong>confidence level</strong> how likely we are to “capture” the population proportion inside our interval if we do this repeatedly.</p>
<p>This is an example of inferential statistics since we are using information from a sample (the statistic <span class="math inline">\(\hat p\)</span>) to infer information about the population (the parameter <span class="math inline">\(p\)</span>)</p>
<section id="steps-for-finding-confidence-intervals---proportions" class="level2" data-number="20.1">
<h2 data-number="20.1" class="anchored" data-anchor-id="steps-for-finding-confidence-intervals---proportions"><span class="header-section-number">20.1</span> Steps for Finding Confidence Intervals - Proportions</h2>
<p>The steps involved to do this are as follows:</p>
<ul>
<li>Take a sample and calculate the sample proportion <span class="math inline">\(\hat p\)</span></li>
<li>Calculate a margin of error <span class="math inline">\(E\)</span> using the formula below. (This tells us roughly how far off <span class="math inline">\(\hat p\)</span> is from <span class="math inline">\(p\)</span>)</li>
<li>Find the interval by adding and subtracting <span class="math inline">\(E\)</span> to <span class="math inline">\(\hat p\)</span>. (This interval tells where we hope to find <span class="math inline">\(p\)</span>)</li>
</ul>
<div id="exm-a-confidence-interval-and-margin-of-error" class="theorem example">
<p><span class="theorem-title"><strong>Example 20.1 (A Confidence Interval and Margin of Error) </strong></span>&nbsp;</p>
<div class="cell">
<p>Suppose we take a sample and collect some data. Then we compute a sample proportion:</p>
<p><span class="math display">\[
\hat p = .41
\]</span></p>
<p>Then using the formula for a confidence interval suppose we find that</p>
<p><span class="math display">\[
E = .03
\]</span></p>
<p>(We will show how to compute this later on. For now just pretend we did it and got <span class="math inline">\(.03\)</span>.)</p>
<p>Subtract <span class="math inline">\(E\)</span> from <span class="math inline">\(\hat p\)</span> to get the <strong>lower endpoint</strong> of the confidence interval:</p>
<p><span class="math display">\[
\hat p - E = .41 - .03 = .38
\]</span></p>
<p>Add <span class="math inline">\(E\)</span> to <span class="math inline">\(\hat p\)</span> to get the <strong>upper endpoint</strong> of the confidence interval:</p>
<p><span class="math display">\[
\hat p + E = .41 + .03 = .44
\]</span></p>
<p>So the confidence interval goes from .38 up to .44. Sometimes we write this like this:</p>
<p><span class="math display">\[
(\hat{p} - E,\ \hat{p} + E) = (.38,.44)
\]</span></p>
<p>Roughly what this says is that we believe the population proportion is <strong>between 38% and 44%</strong>.</p>
<p>Exactly how confident and in what sense the above is true we will see below.</p>
</div>
<p><span class="math display">\[ \tag*{$\blacksquare$} \]</span></p>
</div>
<p>Next we look at how we come up with <span class="math inline">\(E\)</span>, the margin of error.</p>
</section>
<section id="margin-of-error-e-for-confidence-intervals---proportions" class="level2" data-number="20.2">
<h2 data-number="20.2" class="anchored" data-anchor-id="margin-of-error-e-for-confidence-intervals---proportions"><span class="header-section-number">20.2</span> Margin of Error E for Confidence Intervals - Proportions</h2>
<p>To find <span class="math inline">\(E\)</span> we have to first decide on a <strong>confidence level.</strong> This is a percentage (something like 90% or 95% or 99%).</p>
<p>The confidence level describes how confident we are that our confidence intervals will contain the population proportion:</p>
<ul>
<li>A confidence level of 95% means that our confidence intervals (<span class="math inline">\(\widehat{p} - E\)</span>, <span class="math inline">\(\widehat{p} + E\)</span>) will contain the population proportion <span class="math inline">\(p\)</span> about 95% of the time.</li>
<li>A confidence level of 99% means that our confidence intervals (<span class="math inline">\(\widehat{p} - E\)</span>, <span class="math inline">\(\widehat{p} + E\)</span>) will contain the population proportion <span class="math inline">\(p\)</span> about 99% of the time.</li>
<li>and so on</li>
</ul>
<p>Another way to put this:</p>
<p>For 95% confidence, this means that if we repeatedly take samples and find a sample proportion <span class="math inline">\(\hat p\)</span>, we can expect to find the population proportion inside our confidence intervals roughly 95% of the time.</p>
<p>This notion of confidence level makes sense only in the context of repeatedly taking confidence intervals for a particular situation.</p>
<p>Of the different confidence levels, by far <strong>the most commonly used confidence interval is one with confidence level 95%.</strong></p>
<p>Once we decide on the confidence level we want to use, we will use the following formula to calculate the margin of error <span class="math inline">\(E\)</span>:</p>
<p><span class="math display">\[
E=(z^\star)\sqrt{\frac{(1-\hat p)(\hat p)}{n}}
\]</span></p>
<p>The <span class="math inline">\(\hat p\)</span> we have and the sample size <span class="math inline">\(n\)</span> we have as well. The <span class="math inline">\(z^\star\)</span> comes from the chosen confidence level. We show where to get it in the next section.</p>
</section>
<section id="critical-value-zstar" class="level2" data-number="20.3">
<h2 data-number="20.3" class="anchored" data-anchor-id="critical-value-zstar"><span class="header-section-number">20.3</span> Critical Value <span class="math inline">\(z^\star\)</span></h2>
<p>The formula for E has something called <span class="math inline">\(z^\star\)</span> in it. This is called the <strong>critical value</strong>. It comes directly from the confidence level. Once you know the confidence interval you are using you can look up the <span class="math inline">\(z^\star\)</span> that goes with that confidence level. Here are the most typical values:</p>
<table class="table">
<thead>
<tr class="header">
<th>Confidence Level</th>
<th>80%</th>
<th>90%</th>
<th>95%</th>
<th>99%</th>
<th>99.9%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(z^\star\)</span></td>
<td>1.282</td>
<td>1.645</td>
<td>1.960</td>
<td>2.576</td>
<td>3.291</td>
</tr>
</tbody>
</table>
<p>As an example, this table says:</p>
<ul>
<li>use 1.645 for the <span class="math inline">\(z^\star\)</span> if you are computing a 90% confidence interval</li>
<li>use 1.960 for the <span class="math inline">\(z^\star\)</span> if you are computing a 95% confidence interval</li>
</ul>
<p>If you ever need a confidence interval for some confidence level not shown in the table above you can compute it yourself using a spreadsheet as follows:</p>
<p><strong>= NORMSINV( (c+1.0)/2)</strong></p>
<p>where c = confidence level as a proportion. For example if the confidence level was 97% (which is not on the table above) then you could get it in a spreadsheet with</p>
<p><strong>=NORMSINV((.97+1.0)/2)</strong></p>
<p>As part of using the normal distribution to find the <span class="math inline">\(z^\star\)</span> we also have to check the technical conditions like in the Central Limit Theorem.</p>
<p>For the above to be valid must have <span class="math inline">\(n(\hat p)&gt;5\)</span> and <span class="math inline">\(n(1-\hat p)&gt;5\)</span>.</p>
</section>
<section id="confidence-interval-calculations---proportions" class="level2" data-number="20.4">
<h2 data-number="20.4" class="anchored" data-anchor-id="confidence-interval-calculations---proportions"><span class="header-section-number">20.4</span> Confidence Interval Calculations - Proportions</h2>
<div id="exm-a-95-percent-confidence-interval" class="theorem example">
<p><span class="theorem-title"><strong>Example 20.2 (A <span class="math inline">\(95\%\)</span> Confidence Interval) </strong></span>&nbsp;</p>
<div class="cell">
<div class="cell-output-display">
<p>Suppose we have a sample proportion of <span class="math inline">\(210\)</span> out of <span class="math inline">\(250\)</span>. Find a <span class="math inline">\(95\%\)</span> confidence interval for this sample proportion.</p>
<p><strong><em>Solution:</em></strong></p>
<p>The sample proportion is <span class="math inline">\(210\)</span> out of <span class="math inline">\(250\)</span>:</p>
<p><span class="math display">\[\begin{equation}
\hat p = \frac{count}{n} = \frac{210}{250} = 0.84
\end{equation}\]</span></p>
<p>Before we start we check the conditions showing we can use z-values from a standard normal distribution here: <span class="math inline">\(n(\hat p)=(250)(0.84)= 210\)</span> and <span class="math inline">\(n(1-\hat p)=(250)(0.16)= 40\)</span></p>
<p>Since these are both at least <span class="math inline">\(5\)</span> we are in good shape.</p>
<p>Next we will calculate the <span class="math inline">\(E\)</span> involved, using the confidence level 95%.</p>
<p>For this confidence level we can look up that the appropriate critical value <span class="math inline">\(z^\star\)</span> to use. In this case it is <span class="math inline">\(z^\star = 1.96\)</span>.</p>
<p>We plug the sample proportion <span class="math inline">\(\hat p=0.84\)</span> and the sample size <span class="math inline">\(n=250\)</span> and the <span class="math inline">\(z^\star\)</span> into our formula for <span class="math inline">\(E\)</span>:</p>
<p><span class="math display">\[\begin{equation}
E=(z^\star)\sqrt{\frac{(1-\hat p)(\hat p)}{n}}
=(1.96)\sqrt{\frac{(1-0.84)(0.84)}{250}}
= 0.045
\end{equation}\]</span></p>
<p>Then we find the two endpoints.</p>
<p>The left one is this:</p>
<p><span class="math display">\[\begin{equation}
\hat p - E = 0.84-0.045 = 0.795
\end{equation}\]</span></p>
<p>The right one is this:</p>
<p><span class="math display">\[\begin{equation}
\hat p + E = 0.84+0.045 = 0.885
\end{equation}\]</span></p>
<p>So the confidence interval for the sample proportion is</p>
<p><span class="math display">\[\begin{equation}
(0.795,0.885)
\end{equation}\]</span></p>
<p>If we wanted this rounded to the nearest percent we would use:</p>
<p><span class="math display">\[\begin{equation}
(80 \% ,88 \%)
\end{equation}\]</span></p>
<p>We could say the confidence interval is from <span class="math inline">\(80 \%\)</span> to <span class="math inline">\(88 \%\)</span>.</p>
<p><span class="math display">\[
\tag*{$\blacksquare$}
\]</span></p>
</div>
</div>
</div>
</section>
<section id="effect-of-changing-confidence-level" class="level2" data-number="20.5">
<h2 data-number="20.5" class="anchored" data-anchor-id="effect-of-changing-confidence-level"><span class="header-section-number">20.5</span> Effect of Changing Confidence Level</h2>
<p>What is the effect of changing the confidence level?</p>
<p>The higher the confidence level, the more sure we are of “capturing” the actual population proportion. But at the same time, the more sure we are of “capturing” the actual population proportion the wider our confidence intervals become.</p>
<ul>
<li>A 95% confidence interval will be wider than a 90% confidence interval.</li>
<li>A 99% confidence interval will be wider than a 95% confidence interval.</li>
<li>and so on</li>
</ul>
<p>It is kind of like if we cast a larger net we will be sure to catch it in the net somewhere, but then we are less sure exactly where it is because the net is bigger.</p>
<p>Let’s see an example where we calculate the confidence interval twice, each time using a different confidence level.</p>
<ul>
<li>First we compute it for 90% confidence level</li>
<li>Second we compute it for 99% confidence level</li>
</ul>
<div id="exm-first-version-90-percent-confidence-level" class="theorem example">
<p><span class="theorem-title"><strong>Example 20.3 (First Version - 90% Confidence Level) </strong></span>&nbsp;</p>
<div class="cell-output-display">
<p>Suppose we have a sample proportion of <span class="math inline">\(50\)</span> out of <span class="math inline">\(125\)</span>. Find a <span class="math inline">\(90\%\)</span> confidence interval for this sample proportion.</p>
<p><strong><em>Solution:</em></strong></p>
<p>The sample proportion is <span class="math inline">\(50\)</span> out of <span class="math inline">\(125\)</span>:</p>
<p><span class="math display">\[\begin{equation}
\hat p = \frac{count}{n} = \frac{50}{125} = 0.4
\end{equation}\]</span></p>
<p>Before we start we check the conditions showing we can use z-values from a standard normal distribution here: <span class="math inline">\(n(\hat p)=(125)(0.4)= 50\)</span> and <span class="math inline">\(n(1-\hat p)=(125)(0.6)= 75\)</span></p>
<p>Since these are both at least <span class="math inline">\(5\)</span> we are in good shape.</p>
<p>Next we will calculate the <span class="math inline">\(E\)</span> involved, using the confidence level 90%.</p>
<p>For this confidence level we can look up that the appropriate critical value <span class="math inline">\(z^\star\)</span> to use. In this case it is <span class="math inline">\(z^\star = 1.645\)</span>.</p>
<p>We plug the sample proportion <span class="math inline">\(\hat p=0.4\)</span> and the sample size <span class="math inline">\(n=125\)</span> and the <span class="math inline">\(z^\star\)</span> into our formula for <span class="math inline">\(E\)</span>:</p>
<p><span class="math display">\[\begin{equation}
E=(z^\star)\sqrt{\frac{(1-\hat p)(\hat p)}{n}}
=(1.645)\sqrt{\frac{(1-0.4)(0.4)}{125}}
= 0.072
\end{equation}\]</span></p>
<p>Then we find the two endpoints.</p>
<p>The left one is this:</p>
<p><span class="math display">\[\begin{equation}
\hat p - E = 0.4-0.072 = 0.328
\end{equation}\]</span></p>
<p>The right one is this:</p>
<p><span class="math display">\[\begin{equation}
\hat p + E = 0.4+0.072 = 0.472
\end{equation}\]</span></p>
<p>So the confidence interval for the sample proportion is</p>
<p><span class="math display">\[\begin{equation}
(0.328,0.472)
\end{equation}\]</span></p>
<p>If we wanted this rounded to the nearest percent we would use:</p>
<p><span class="math display">\[\begin{equation}
(33 \% ,47 \%)
\end{equation}\]</span></p>
<p>We could say the confidence interval is from <span class="math inline">\(33 \%\)</span> to <span class="math inline">\(47 \%\)</span>.</p>
<p><span class="math display">\[
\tag*{$\blacksquare$}
\]</span></p>
</div>
</div>
<p>Now let’s do that last one over with a 99% confidence level.</p>
<div id="exm-second-version-99-percent-confidence-level" class="theorem example">
<p><span class="theorem-title"><strong>Example 20.4 (Second Version - <span class="math inline">\(99\%\)</span> Confidence Level) </strong></span>&nbsp;</p>
<div class="cell">
<div class="cell-output-display">
<p>Suppose we have a sample proportion of <span class="math inline">\(50\)</span> out of <span class="math inline">\(125\)</span>. Find a <span class="math inline">\(99\%\)</span> confidence interval for this sample proportion.</p>
<p><strong><em>Solution:</em></strong></p>
<p>The sample proportion is <span class="math inline">\(50\)</span> out of <span class="math inline">\(125\)</span>:</p>
<p><span class="math display">\[\begin{equation}
\hat p = \frac{count}{n} = \frac{50}{125} = 0.4
\end{equation}\]</span></p>
<p>Before we start we check the conditions showing we can use z-values from a standard normal distribution here: <span class="math inline">\(n(\hat p)=(125)(0.4)= 50\)</span> and <span class="math inline">\(n(1-\hat p)=(125)(0.6)= 75\)</span></p>
<p>Since these are both at least <span class="math inline">\(5\)</span> we are in good shape.</p>
<p>Next we will calculate the <span class="math inline">\(E\)</span> involved, using the confidence level 99%.</p>
<p>For this confidence level we can look up that the appropriate critical value <span class="math inline">\(z^\star\)</span> to use. In this case it is <span class="math inline">\(z^\star = 2.576\)</span>.</p>
<p>We plug the sample proportion <span class="math inline">\(\hat p=0.4\)</span> and the sample size <span class="math inline">\(n=125\)</span> and the <span class="math inline">\(z^\star\)</span> into our formula for <span class="math inline">\(E\)</span>:</p>
<p><span class="math display">\[\begin{equation}
E=(z^\star)\sqrt{\frac{(1-\hat p)(\hat p)}{n}}
=(2.576)\sqrt{\frac{(1-0.4)(0.4)}{125}}
= 0.113
\end{equation}\]</span></p>
<p>Then we find the two endpoints.</p>
<p>The left one is this:</p>
<p><span class="math display">\[\begin{equation}
\hat p - E = 0.4-0.113 = 0.287
\end{equation}\]</span></p>
<p>The right one is this:</p>
<p><span class="math display">\[\begin{equation}
\hat p + E = 0.4+0.113 = 0.513
\end{equation}\]</span></p>
<p>So the confidence interval for the sample proportion is</p>
<p><span class="math display">\[\begin{equation}
(0.287,0.513)
\end{equation}\]</span></p>
<p>If we wanted this rounded to the nearest percent we would use:</p>
<p><span class="math display">\[\begin{equation}
(29 \% ,51 \%)
\end{equation}\]</span></p>
<p>We could say the confidence interval is from <span class="math inline">\(29 \%\)</span> to <span class="math inline">\(51 \%\)</span>.</p>
<p><span class="math display">\[
\tag*{$\blacksquare$}
\]</span></p>
</div>
</div>
</div>
<p>Which confidence interval was wider in the above?</p>
<p>The 99% confidence level one.</p>
<p>To be more confident that your confidence interval contains the population proportion it must be wider.</p>
<p>Of course this means your estimate is less accurate and that is reflected in the range of the interval being larger.</p>
</section>
<section id="applications-of-confidence-intervals" class="level2" data-number="20.6">
<h2 data-number="20.6" class="anchored" data-anchor-id="applications-of-confidence-intervals"><span class="header-section-number">20.6</span> Applications of Confidence Intervals</h2>
<div id="exm-shopping-app-usage" class="theorem example">
<p><span class="theorem-title"><strong>Example 20.5 (Shopping App Usage) </strong></span>&nbsp;</p>
<div class="cell">
<div class="cell-output-display">
<p>A department store thinks that <span class="math inline">\(40\%\)</span> of their customers would use a shopping app while in-store. They poll <span class="math inline">\(300\)</span> users one day and find out that <span class="math inline">\(78\)</span> of them would use such an app. Find a <span class="math inline">\(90\%\)</span> confidence interval for this sample proportion.</p>
<p><strong><em>Solution:</em></strong></p>
<p>The sample proportion is <span class="math inline">\(78\)</span> out of <span class="math inline">\(300\)</span>:</p>
<p><span class="math display">\[\begin{equation}
\hat p = \frac{count}{n} = \frac{78}{300} = 0.26
\end{equation}\]</span></p>
<p>Before we start we check the conditions showing we can use z-values from a standard normal distribution here: <span class="math inline">\(n(\hat p)=(300)(0.26)= 78\)</span> and <span class="math inline">\(n(1-\hat p)=(300)(0.74)= 222\)</span></p>
<p>Since these are both at least <span class="math inline">\(5\)</span> we are in good shape.</p>
<p>Next we will calculate the <span class="math inline">\(E\)</span> involved, using the confidence level 90%.</p>
<p>For this confidence level we can look up that the appropriate critical value <span class="math inline">\(z^\star\)</span> to use. In this case it is <span class="math inline">\(z^\star = 1.645\)</span>.</p>
<p>We plug the sample proportion <span class="math inline">\(\hat p=0.26\)</span> and the sample size <span class="math inline">\(n=300\)</span> and the <span class="math inline">\(z^\star\)</span> into our formula for <span class="math inline">\(E\)</span>:</p>
<p><span class="math display">\[\begin{equation}
E=(z^\star)\sqrt{\frac{(1-\hat p)(\hat p)}{n}}
=(1.645)\sqrt{\frac{(1-0.26)(0.26)}{300}}
= 0.042
\end{equation}\]</span></p>
<p>Then we find the two endpoints.</p>
<p>The left one is this:</p>
<p><span class="math display">\[\begin{equation}
\hat p - E = 0.26-0.042 = 0.218
\end{equation}\]</span></p>
<p>The right one is this:</p>
<p><span class="math display">\[\begin{equation}
\hat p + E = 0.26+0.042 = 0.302
\end{equation}\]</span></p>
<p>So the confidence interval for the sample proportion is</p>
<p><span class="math display">\[\begin{equation}
(0.218,0.302)
\end{equation}\]</span></p>
<p>If we wanted this rounded to the nearest percent we would use:</p>
<p><span class="math display">\[\begin{equation}
(22 \% ,30 \%)
\end{equation}\]</span></p>
<p>We could say the confidence interval is from <span class="math inline">\(22 \%\)</span> to <span class="math inline">\(30 \%\)</span>.</p>
<p>The confidence interval does not contain <span class="math inline">\(40\%\)</span> and so probably the store is overestimating what proportion of their customers would use such an app. It appears to be somewhat less than <span class="math inline">\(40\%\)</span>.</p>
<p><span class="math display">\[
\tag*{$\blacksquare$}
\]</span></p>
</div>
</div>
</div>
<p>In the next example we estimate the chance of being out of stock for some item we are selling.</p>
<div id="exm-estimating-out-of-stock" class="theorem example">
<p><span class="theorem-title"><strong>Example 20.6 (Estimating Out Of Stock) </strong></span>&nbsp;</p>
<div class="cell">
<div class="cell-output-display">
<p>A store had some item out of stock in <span class="math inline">\(26\)</span> of the past <span class="math inline">\(208\)</span> weeks (the last 4 years). Calculate a <span class="math inline">\(90\%\)</span> confidence interval estimate for the proportion of weeks this item is out of stock.</p>
<p><strong><em>Solution:</em></strong></p>
<p>The sample proportion is <span class="math inline">\(26\)</span> out of <span class="math inline">\(208\)</span>:</p>
<p><span class="math display">\[\begin{equation}
\hat p = \frac{count}{n} = \frac{26}{208} = 0.125
\end{equation}\]</span></p>
<p>Before we start we check the conditions showing we can use z-values from a standard normal distribution here: <span class="math inline">\(n(\hat p)=(208)(0.125)= 26\)</span> and <span class="math inline">\(n(1-\hat p)=(208)(0.875)= 182\)</span></p>
<p>Since these are both at least <span class="math inline">\(5\)</span> we are in good shape.</p>
<p>Next we will calculate the <span class="math inline">\(E\)</span> involved, using the confidence level 90%.</p>
<p>For this confidence level we can look up that the appropriate critical value <span class="math inline">\(z^\star\)</span> to use. In this case it is <span class="math inline">\(z^\star = 1.645\)</span>.</p>
<p>We plug the sample proportion <span class="math inline">\(\hat p=0.125\)</span> and the sample size <span class="math inline">\(n=208\)</span> and the <span class="math inline">\(z^\star\)</span> into our formula for <span class="math inline">\(E\)</span>:</p>
<p><span class="math display">\[\begin{equation}
E=(z^\star)\sqrt{\frac{(1-\hat p)(\hat p)}{n}}
=(1.645)\sqrt{\frac{(1-0.125)(0.125)}{208}}
= 0.038
\end{equation}\]</span></p>
<p>Then we find the two endpoints.</p>
<p>The left one is this:</p>
<p><span class="math display">\[\begin{equation}
\hat p - E = 0.125-0.038 = 0.087
\end{equation}\]</span></p>
<p>The right one is this:</p>
<p><span class="math display">\[\begin{equation}
\hat p + E = 0.125+0.038 = 0.163
\end{equation}\]</span></p>
<p>So the confidence interval for the sample proportion is</p>
<p><span class="math display">\[\begin{equation}
(0.087,0.163)
\end{equation}\]</span></p>
<p>If we wanted this rounded to the nearest percent we would use:</p>
<p><span class="math display">\[\begin{equation}
(9 \% ,16 \%)
\end{equation}\]</span></p>
<p>We could say the confidence interval is from <span class="math inline">\(9 \%\)</span> to <span class="math inline">\(16 \%\)</span>.</p>
<p>Our estimate is between <span class="math inline">\(9 \%\)</span> and <span class="math inline">\(16 \%\)</span></p>
<p><span class="math display">\[
\tag*{$\blacksquare$}
\]</span></p>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./sample-proportions-distribution.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Sampling Distribution of Sample Proportions</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./hypothesis-testing-proportions.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Hypothesis Testing - Proportions</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>